### ISSUE TITLE
There is a question, thank you very much for your answer

### ISSUE THREAD

**Issue by houxushi** [VerwimpEli/SSLAD_Track_3#2]
The following is the error message：

Traceback (most recent call last):
  File "classification.py", line 106, in <module>
    main()
  File "classification.py", line 63, in main
    train_sets = create_train_set(args.root, img_size)
  File "/workspace/ICCV/track3A/classification_util.py", line 53, in create_train_set
    train_sets = [hc.get_matching_set(root, 'val', mf, img_size=img_size, transform=transform) for mf in match_fn]
  File "/workspace/ICCV/track3A/classification_util.py", line 53, in <listcomp>
    train_sets = [hc.get_matching_set(root, 'val', mf, img_size=img_size, transform=transform) for mf in match_fn]
  File "/workspace/ICCV/track3A/haitain_classification.py", line 272, in get_matching_set
    obj_dic, img_dic = _load_obj_img_dic(root, split)
  File "/workspace/ICCV/track3A/haitain_classification.py", line 231, in _load_obj_img_dic
    _correct_data(img_dic, obj_dic, split)
  File "/workspace/ICCV/track3A/haitain_classification.py", line 213, in _correct_data
    img_dic[key]['time'] = img_dic[key]['time'].strip()
KeyError: 'time'

I checked the label file, there is no "time" key in it，So I am very confused, hope you can answer, thank you very much！

**Comment by VerwimpEli** [comment]
Hi, you're correct. The annotations are different (eg. with the time and date) for this track, so we had to upload them separately. You can find the download links here: https://competitions.codalab.org/competitions/33830#participate. 

Hope this resolves the issue!

**Comment by houxushi** [comment]
> Hi, you're correct. The annotations are different (eg. with the time and date) for this track, so we had to upload them separately. You can find the download links here: https://competitions.codalab.org/competitions/33830#participate.
> 
> Hope this resolves the issue!

Thank you very much!I have solved this problem!
